include:
  - component: gitlab.com/platform_engineering/platform-components/docker-factory/docker-factory@main
    inputs:
      language: bun
      port: "4000"
      entrypoint: "dist/index.js"
      artifact_paths: "dist"
      dep_files: "package.json bun.lock bunfig.toml"
