# scripts to run before `bun run`-ing a file or script
# register plugins by adding them to this list
preload = ['src/instrumentation.ts']
logLevel = "debug"

[run]
# equivalent to `bun --bun` for all `bun run` commands
bun = true

[install.lockfile]
path = "bun.lockb"

[install]
globalThis.CN_ROOT = "/usr/src/app"
globalThis.CXXCBC_CACHE_DIR = "/usr/src/app/deps/couchbase-cxx-cache"

[build]
target = "bun"
