---
name: "Setup Environment"
description: "Sets up common actions and environment with caching optimizations"

inputs:
  bun-version:
    description: "Bun version to install"
    required: false
    default: "latest"
  enable-bun-cache:
    description: "Enable Bun dependency caching"
    required: false
    default: "true"

outputs:
  bun-cache-hit:
    description: "Whether Bun cache was restored"
    value: ${{ steps.bun-cache.outputs.cache-hit }}
  buildx-name:
    description: "Name of the Buildx builder"
    value: ${{ steps.buildx.outputs.name }}

runs:
  using: "composite"
  steps:
    # -------------------------------------------------------------------------
    # Step 1: Docker Build Cloud setup (native ARM builds, no QEMU needed)
    # -------------------------------------------------------------------------
    - name: Set up Docker Buildx with Build Cloud
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: cloud
        endpoint: zx8086/cldbuild
        install: true

    # -------------------------------------------------------------------------
    # Step 2: Bun setup with dependency caching
    # -------------------------------------------------------------------------
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Get Bun cache directory
      id: bun-cache-dir
      shell: bash
      run: |
        # Bun stores its cache in ~/.bun/install/cache
        echo "dir=${HOME}/.bun/install/cache" >> $GITHUB_OUTPUT

    - name: Restore Bun dependency cache
      id: bun-cache
      if: inputs.enable-bun-cache == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.bun-cache-dir.outputs.dir }}
          node_modules
        key: bun-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('bun.lockb', 'package.json') }}
        restore-keys: |
          bun-${{ runner.os }}-${{ runner.arch }}-

    - name: Log cache status
      shell: bash
      run: |
        if [ "${{ steps.bun-cache.outputs.cache-hit }}" == "true" ]; then
          echo "Bun cache restored successfully"
        else
          echo "Bun cache miss - dependencies will be downloaded"
        fi

    # -------------------------------------------------------------------------
    # Step 3: Environment variables for BuildKit optimization
    # -------------------------------------------------------------------------
    - name: Set Environment Variables
      shell: bash
      run: |
        # BuildKit settings
        echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
        echo "COMPOSE_DOCKER_CLI_BUILD=1" >> $GITHUB_ENV
        echo "BUILDX_NO_DEFAULT_LOAD=true" >> $GITHUB_ENV
        echo "BUILDKIT_PROGRESS=plain" >> $GITHUB_ENV

        # Builder name for reference
        echo "BUILDX_BUILDER=${{ steps.buildx.outputs.name }}" >> $GITHUB_ENV

    # -------------------------------------------------------------------------
    # Step 4: Summary
    # -------------------------------------------------------------------------
    - name: Setup Summary
      shell: bash
      run: |
        echo "Environment setup complete:"
        echo "  - Bun: $(bun --version)"
        echo "  - Buildx: ${{ steps.buildx.outputs.name }} (Docker Build Cloud)"
        echo "  - Bun cache: ${{ steps.bun-cache.outputs.cache-hit == 'true' && 'restored' || 'miss' }}"
        echo "  - Platforms: linux/amd64, linux/arm64 (native)"
