# .github/actions/setup-environment/action.yml
name: "Setup Environment"
description: "Sets up common actions and environment"

runs:
  using: "composite"
  steps:
    - name: Cache GitHub Actions
      uses: actions/cache@v3
      with:
        path: ~/.cache/github-actions
        key: ${{ runner.os }}-actions-${{ github.workflow }}-${{ hashFiles('**/.github/workflows/*.yml') }}
        restore-keys: |
          ${{ runner.os }}-actions-${{ github.workflow }}-
          ${{ runner.os }}-actions-

    - name: Set Environment Variables
      shell: bash
      run: |
        echo "ACTIONS_CACHE_DIR=~/.cache/github-actions" >> $GITHUB_ENV
        echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
        echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
        echo "COMPOSE_DOCKER_CLI_BUILD=1" >> $GITHUB_ENV
        echo "BUILDX_NO_DEFAULT_LOAD=true" >> $GITHUB_ENV
        echo "BUILDKIT_INLINE_CACHE=1" >> $GITHUB_ENV
        echo "BUILDX_CACHE_TTL=168h" >> $GITHUB_ENV
        echo "BUILDKIT_PROGRESS=plain" >> $GITHUB_ENV
        echo "BUILDKIT_STEP_LOG_MAX_SIZE=10000000" >> $GITHUB_ENV
        echo "BUILDKIT_STEP_LOG_MAX_SPEED=10000000" >> $GITHUB_ENV
        echo "BUILDKIT_CACHE_MOUNT_NS=buildkit-cache" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: cloud
        endpoint: "zx8086/cldbuild"
        install: true
        platforms: linux/arm64,linux/amd64

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
