name: "Setup Environment"
description: "Sets up common actions and environment"

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
        driver-opts: |
          image=moby/buildkit:latest
          network=host
        buildkitd-flags: --debug

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Set Environment Variables
      shell: bash
      run: |
        echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
        echo "COMPOSE_DOCKER_CLI_BUILD=1" >> $GITHUB_ENV
        echo "BUILDX_NO_DEFAULT_LOAD=true" >> $GITHUB_ENV
        echo "BUILDKIT_INLINE_CACHE=1" >> $GITHUB_ENV
        echo "BUILDKIT_PROGRESS=plain" >> $GITHUB_ENV

    - name: Install verification tools
      shell: bash
      run: |
        # Create directories
        mkdir -p "${GITHUB_WORKSPACE}/bin"
        
        # Detect architecture
        ARCH=$(uname -m)
        case $ARCH in
          x86_64) ARCH_SUFFIX="amd64" ;;
          aarch64|arm64) ARCH_SUFFIX="arm64" ;;
          *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
        esac

        # Install cosign
        curl -Lo "${GITHUB_WORKSPACE}/bin/cosign" "https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-${ARCH_SUFFIX}"
        chmod +x "${GITHUB_WORKSPACE}/bin/cosign"

        # Install syft
        SYFT_RELEASE=$(curl -s https://api.github.com/repos/anchore/syft/releases/latest | grep -o '"tag_name": ".*"' | cut -d'"' -f4)
        SYFT_VERSION_NO_V=$(echo "${SYFT_RELEASE}" | sed 's/^v//')
        curl -Lo syft.tar.gz "https://github.com/anchore/syft/releases/download/${SYFT_RELEASE}/syft_${SYFT_VERSION_NO_V}_linux_${ARCH_SUFFIX}.tar.gz"
        tar xzf syft.tar.gz syft
        mv syft "${GITHUB_WORKSPACE}/bin/"
        rm syft.tar.gz

        # Add to PATH
        echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

        # Verify installations
        "${GITHUB_WORKSPACE}/bin/cosign" version || true
        "${GITHUB_WORKSPACE}/bin/syft" --version || true
