# .github/actions/setup-environment/action.yml

name: "Setup Environment"
description: "Sets up common actions and environment"

runs:
  using: "composite"
  steps:
    - name: Cache GitHub Actions
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/github-actions
          ~/actions-runner/_work/_actions
          ~/actions-runner/_work/_tool
        key: ${{ runner.os }}-actions-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-actions-

    - name: Cache Docker BuildKit
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set Environment Variables
      shell: bash
      run: |
        echo "ACTIONS_CACHE_DIR=~/.cache/github-actions" >> $GITHUB_ENV
        echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
        echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
        echo "COMPOSE_DOCKER_CLI_BUILD=1" >> $GITHUB_ENV
        echo "BUILDX_NO_DEFAULT_LOAD=true" >> $GITHUB_ENV
        echo "BUILDKIT_INLINE_CACHE=1" >> $GITHUB_ENV
        echo "BUILDX_CACHE_TTL=168h" >> $GITHUB_ENV
        echo "BUILDKIT_PROGRESS=plain" >> $GITHUB_ENV
        echo "BUILDKIT_STEP_LOG_MAX_SIZE=10000000" >> $GITHUB_ENV
        echo "BUILDKIT_STEP_LOG_MAX_SPEED=10000000" >> $GITHUB_ENV
        echo "BUILDKIT_CACHE_MOUNT_NS=buildkit-cache" >> $GITHUB_ENV

    - name: Install verification tools
      continue-on-error: true
      shell: bash
      run: |
        # Install cosign for attestation verification
        curl -Lo cosign https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
        chmod +x cosign
        sudo mv cosign /usr/local/bin/

        # Install syft for SBOM generation/verification
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=moby/buildkit:latest
          network=host
        buildkitd-flags: --debug
        config: |
          [worker.oci]
            max-parallelism = 2
          [worker.containerd]
            gc = true
            gc-keepstorage = 20GB
        platforms: linux/arm64,linux/amd64

    - name: Pre-fetch common actions
      shell: bash
      run: |
        mkdir -p ~/actions-runner/_work/_actions
        for action in "actions/checkout@v4" "docker/metadata-action@v5" "actions/cache@v3" "github/codeql-action@v3" "docker/login-action@v3" "docker/build-push-action@v6" "actions/upload-artifact@v4"; do
          if [ ! -d "~/actions-runner/_work/_actions/${action%@*}/${action#*@}" ]; then
            git clone --depth 1 -b ${action#*@} https://github.com/${action%@*}.git ~/actions-runner/_work/_actions/${action%@*}/${action#*@}
          fi
        done

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
