/* src/config/envMapping.ts */
// Pillar 2: Environment Variable Mapping
// Aligned with migrate reference pattern

// Consolidated environment variable mapping for all configuration sections
export const envVarMapping = {
  application: {
    LOG_LEVEL: "LOG_LEVEL",
    YOGA_RESPONSE_CACHE_TTL: "YOGA_RESPONSE_CACHE_TTL",
    PORT: "PORT",
    ALLOWED_ORIGINS: "ALLOWED_ORIGINS",
    BASE_URL: "BASE_URL",
  },

  capella: {
    COUCHBASE_URL: "COUCHBASE_URL",
    COUCHBASE_USERNAME: "COUCHBASE_USERNAME",
    COUCHBASE_PASSWORD: "COUCHBASE_PASSWORD",
    COUCHBASE_BUCKET: "COUCHBASE_BUCKET",
    COUCHBASE_SCOPE: "COUCHBASE_SCOPE",
    COUCHBASE_COLLECTION: "COUCHBASE_COLLECTION",
    COUCHBASE_KV_TIMEOUT: "COUCHBASE_KV_TIMEOUT",
    COUCHBASE_KV_DURABLE_TIMEOUT: "COUCHBASE_KV_DURABLE_TIMEOUT",
    COUCHBASE_QUERY_TIMEOUT: "COUCHBASE_QUERY_TIMEOUT",
    COUCHBASE_ANALYTICS_TIMEOUT: "COUCHBASE_ANALYTICS_TIMEOUT",
    COUCHBASE_SEARCH_TIMEOUT: "COUCHBASE_SEARCH_TIMEOUT",
    COUCHBASE_CONNECT_TIMEOUT: "COUCHBASE_CONNECT_TIMEOUT",
    COUCHBASE_BOOTSTRAP_TIMEOUT: "COUCHBASE_BOOTSTRAP_TIMEOUT",
  },

  runtime: {
    NODE_ENV: "NODE_ENV",
    CN_ROOT: "CN_ROOT",
    CN_CXXCBC_CACHE_DIR: "CN_CXXCBC_CACHE_DIR",
    SOURCE_MAP_SUPPORT: "SOURCE_MAP_SUPPORT",
    PRESERVE_SOURCE_MAPS: "PRESERVE_SOURCE_MAPS",
    BUN_CONFIG_DNS_TIME_TO_LIVE_SECONDS: "BUN_CONFIG_DNS_TIME_TO_LIVE_SECONDS",
  },

  deployment: {
    BASE_URL: "BASE_URL",
    HOSTNAME: "HOSTNAME",
    INSTANCE_ID: "INSTANCE_ID",
    CONTAINER_ID: "CONTAINER_ID",
    K8S_POD_NAME: "K8S_POD_NAME",
    K8S_NAMESPACE: "K8S_NAMESPACE",
  },

  telemetry: {
    // Core telemetry settings
    ENABLE_OPENTELEMETRY: "ENABLE_OPENTELEMETRY",
    SERVICE_NAME: "OTEL_SERVICE_NAME", // Standard OTEL env var
    SERVICE_VERSION: "OTEL_SERVICE_VERSION", // Standard OTEL env var
    DEPLOYMENT_ENVIRONMENT: "DEPLOYMENT_ENVIRONMENT",

    // Standard OTEL exporter endpoint environment variables
    OTLP_ENDPOINT: "OTEL_EXPORTER_OTLP_ENDPOINT", // Base endpoint (fallback)
    TRACES_ENDPOINT: "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT",
    METRICS_ENDPOINT: "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT",
    LOGS_ENDPOINT: "OTEL_EXPORTER_OTLP_LOGS_ENDPOINT",

    // Interval settings
    METRIC_READER_INTERVAL: "METRIC_READER_INTERVAL",
    SUMMARY_LOG_INTERVAL: "SUMMARY_LOG_INTERVAL",

    // Export settings (2025 compliance)
    EXPORT_TIMEOUT_MS: "EXPORT_TIMEOUT_MS",
    BATCH_SIZE: "BATCH_SIZE",
    MAX_QUEUE_SIZE: "MAX_QUEUE_SIZE",
    SAMPLING_RATE: "SAMPLING_RATE",

    // Circuit breaker settings
    CIRCUIT_BREAKER_THRESHOLD: "CIRCUIT_BREAKER_THRESHOLD",
    CIRCUIT_BREAKER_TIMEOUT_MS: "CIRCUIT_BREAKER_TIMEOUT_MS",

    // Log-level specific sampling rates
    LOG_SAMPLING_DEBUG: "LOG_SAMPLING_DEBUG",
    LOG_SAMPLING_INFO: "LOG_SAMPLING_INFO",
    LOG_SAMPLING_WARN: "LOG_SAMPLING_WARN",
    LOG_SAMPLING_ERROR: "LOG_SAMPLING_ERROR",

    // Metric sampling rates by category (2025 standard)
    METRIC_SAMPLING_BUSINESS: "METRIC_SAMPLING_BUSINESS",
    METRIC_SAMPLING_TECHNICAL: "METRIC_SAMPLING_TECHNICAL",
    METRIC_SAMPLING_INFRASTRUCTURE: "METRIC_SAMPLING_INFRASTRUCTURE",
    METRIC_SAMPLING_DEBUG: "METRIC_SAMPLING_DEBUG",

    // Log retention policy
    LOG_RETENTION_DEBUG_DAYS: "LOG_RETENTION_DEBUG_DAYS",
    LOG_RETENTION_INFO_DAYS: "LOG_RETENTION_INFO_DAYS",
    LOG_RETENTION_WARN_DAYS: "LOG_RETENTION_WARN_DAYS",
    LOG_RETENTION_ERROR_DAYS: "LOG_RETENTION_ERROR_DAYS",
  },
} as const;

// Environment variable path mapping for error reporting
// Maps config paths to environment variable names
export function getEnvVarPath(configPath: string): string | undefined {
  const mapping: Record<string, string> = {
    // Application section
    "application.LOG_LEVEL": "LOG_LEVEL",
    "application.YOGA_RESPONSE_CACHE_TTL": "YOGA_RESPONSE_CACHE_TTL",
    "application.PORT": "PORT",
    "application.ALLOWED_ORIGINS": "ALLOWED_ORIGINS",
    "application.BASE_URL": "BASE_URL",

    // Capella section
    "capella.COUCHBASE_URL": "COUCHBASE_URL",
    "capella.COUCHBASE_USERNAME": "COUCHBASE_USERNAME",
    "capella.COUCHBASE_PASSWORD": "COUCHBASE_PASSWORD",
    "capella.COUCHBASE_BUCKET": "COUCHBASE_BUCKET",
    "capella.COUCHBASE_SCOPE": "COUCHBASE_SCOPE",
    "capella.COUCHBASE_COLLECTION": "COUCHBASE_COLLECTION",
    "capella.COUCHBASE_KV_TIMEOUT": "COUCHBASE_KV_TIMEOUT",
    "capella.COUCHBASE_KV_DURABLE_TIMEOUT": "COUCHBASE_KV_DURABLE_TIMEOUT",
    "capella.COUCHBASE_QUERY_TIMEOUT": "COUCHBASE_QUERY_TIMEOUT",
    "capella.COUCHBASE_ANALYTICS_TIMEOUT": "COUCHBASE_ANALYTICS_TIMEOUT",
    "capella.COUCHBASE_SEARCH_TIMEOUT": "COUCHBASE_SEARCH_TIMEOUT",
    "capella.COUCHBASE_CONNECT_TIMEOUT": "COUCHBASE_CONNECT_TIMEOUT",
    "capella.COUCHBASE_BOOTSTRAP_TIMEOUT": "COUCHBASE_BOOTSTRAP_TIMEOUT",

    // Runtime section
    "runtime.NODE_ENV": "NODE_ENV",
    "runtime.CN_ROOT": "CN_ROOT",
    "runtime.CN_CXXCBC_CACHE_DIR": "CN_CXXCBC_CACHE_DIR",
    "runtime.SOURCE_MAP_SUPPORT": "SOURCE_MAP_SUPPORT",
    "runtime.PRESERVE_SOURCE_MAPS": "PRESERVE_SOURCE_MAPS",
    "runtime.BUN_CONFIG_DNS_TIME_TO_LIVE_SECONDS": "BUN_CONFIG_DNS_TIME_TO_LIVE_SECONDS",

    // Deployment section
    "deployment.BASE_URL": "BASE_URL",
    "deployment.HOSTNAME": "HOSTNAME",
    "deployment.INSTANCE_ID": "INSTANCE_ID",
    "deployment.CONTAINER_ID": "CONTAINER_ID",
    "deployment.K8S_POD_NAME": "K8S_POD_NAME",
    "deployment.K8S_NAMESPACE": "K8S_NAMESPACE",

    // Telemetry section (uses OTEL standard names)
    "telemetry.ENABLE_OPENTELEMETRY": "ENABLE_OPENTELEMETRY",
    "telemetry.SERVICE_NAME": "OTEL_SERVICE_NAME",
    "telemetry.SERVICE_VERSION": "OTEL_SERVICE_VERSION",
    "telemetry.DEPLOYMENT_ENVIRONMENT": "DEPLOYMENT_ENVIRONMENT",
    "telemetry.TRACES_ENDPOINT": "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT",
    "telemetry.METRICS_ENDPOINT": "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT",
    "telemetry.LOGS_ENDPOINT": "OTEL_EXPORTER_OTLP_LOGS_ENDPOINT",
    "telemetry.METRIC_READER_INTERVAL": "METRIC_READER_INTERVAL",
    "telemetry.SUMMARY_LOG_INTERVAL": "SUMMARY_LOG_INTERVAL",
    "telemetry.EXPORT_TIMEOUT_MS": "EXPORT_TIMEOUT_MS",
    "telemetry.BATCH_SIZE": "BATCH_SIZE",
    "telemetry.MAX_QUEUE_SIZE": "MAX_QUEUE_SIZE",
    "telemetry.SAMPLING_RATE": "SAMPLING_RATE",
    "telemetry.CIRCUIT_BREAKER_THRESHOLD": "CIRCUIT_BREAKER_THRESHOLD",
    "telemetry.CIRCUIT_BREAKER_TIMEOUT_MS": "CIRCUIT_BREAKER_TIMEOUT_MS",
  };

  return mapping[configPath];
}
